# Generated by Django 2.0.2 on 2018-03-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180319_1242'),
        ('articles', '0008_auto_20180319_1447'),
    ]

    operations = [
    ]
